server:
  port: 3002

spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${server.port}:${random.value}
        healthCheckPath: ${management.server.servlet.context-path}/health
        healthCheckInterval: 15s
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    companyExchange: company.exchange
    queue: user.queue
    routingkey: user.routingkey
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging.level:
  org.springframework.cloud:
    consul: DEBUG